export const GET_ASSET_LIST_REQUEST = 'GET_ASSET_LIST_REQUEST'
export const GET_ASSET_LIST_SUCCESS = 'GET_ASSET_LIST_SUCCESS'
export const GET_ASSET_LIST_ERROR = 'GET_ASSET_LIST_ERROR'

export const UPDATE_ASSET_REQUEST = 'UPDATE_ASSET_REQUEST'
export const UPDATE_ASSET_SUCCESS = 'UPDATE_ASSET_SUCCESS'
export const UPDATE_ASSET_ERROR = 'UPDATE_ASSET_ERROR'

export const PREVIEW_ASSET_CHANGE = 'PREVIEW_ASSET_CHANGE'

export const ON_ASSET_CLICK = 'ON_ASSET_CLICK'
export const ON_PRESS_EDIT = 'ON_PRESS_EDIT'
export const ON_PRESS_CANCEL = 'ON_PRESS_CANCEL'
export const ON_PRESS_SAVE = 'ON_PRESS_SAVE'

export const MAP_CONTAINER_TOGGLE_RIGHT_DRAWER = 'MAP_CONTAINER_TOGGLE_RIGHT_DRAWER'
export const SELECT_HEALTH = 'SELECT_HEALTH'
